#include <Box2D/Box2D.h>

#include <Box2D/Collision/b2BroadPhase.cpp>
#include <Box2D/Collision/b2CollideCircle.cpp>
#include <Box2D/Collision/b2CollideEdge.cpp>
#include <Box2D/Collision/b2CollidePolygon.cpp>
#include <Box2D/Collision/b2Collision.cpp>
#include <Box2D/Collision/b2Distance.cpp>
#include <Box2D/Collision/b2DynamicTree.cpp>
#include <Box2D/Collision/b2TimeOfImpact.cpp>
#include <Box2D/Collision/Shapes/b2ChainShape.cpp>
#include <Box2D/Collision/Shapes/b2CircleShape.cpp>
#include <Box2D/Collision/Shapes/b2EdgeShape.cpp>
#include <Box2D/Collision/Shapes/b2PolygonShape.cpp>
#include <Box2D/Common/b2BlockAllocator.cpp>
#include <Box2D/Common/b2Draw.cpp>
#include <Box2D/Common/b2FreeList.cpp>
#include <Box2D/Common/b2Math.cpp>
#include <Box2D/Common/b2Settings.cpp>
#include <Box2D/Common/b2StackAllocator.cpp>
#include <Box2D/Common/b2Timer.cpp>
#include <Box2D/Common/b2TrackedBlock.cpp>
#include <Box2D/Dynamics/b2Body.cpp>
#include <Box2D/Dynamics/b2ContactManager.cpp>
#include <Box2D/Dynamics/b2Fixture.cpp>
#include <Box2D/Dynamics/b2Island.cpp>
#include <Box2D/Dynamics/b2World.cpp>
#include <Box2D/Dynamics/b2WorldCallbacks.cpp>
#include <Box2D/Dynamics/Contacts/b2CircleContact.cpp>
#include <Box2D/Dynamics/Contacts/b2Contact.cpp>
#include <Box2D/Dynamics/Contacts/b2ContactSolver.cpp>
#include <Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp>
#include <Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp>
#include <Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp>
#include <Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp>
#include <Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp>
#include <Box2D/Dynamics/Contacts/b2PolygonContact.cpp>
#include <Box2D/Dynamics/Joints/b2DistanceJoint.cpp>
#include <Box2D/Dynamics/Joints/b2FrictionJoint.cpp>
#include <Box2D/Dynamics/Joints/b2GearJoint.cpp>
#include <Box2D/Dynamics/Joints/b2Joint.cpp>
#include <Box2D/Dynamics/Joints/b2MotorJoint.cpp>
#include <Box2D/Dynamics/Joints/b2MouseJoint.cpp>
#include <Box2D/Dynamics/Joints/b2PrismaticJoint.cpp>
#include <Box2D/Dynamics/Joints/b2PulleyJoint.cpp>
#include <Box2D/Dynamics/Joints/b2RevoluteJoint.cpp>
#include <Box2D/Dynamics/Joints/b2RopeJoint.cpp>
#include <Box2D/Dynamics/Joints/b2WeldJoint.cpp>
#include <Box2D/Dynamics/Joints/b2WheelJoint.cpp>
#include <Box2D/Particle/b2Particle.cpp>
#include <Box2D/Particle/b2ParticleGroup.cpp>
#include <Box2D/Particle/b2ParticleSystem.cpp>
#include <Box2D/Particle/b2VoronoiDiagram.cpp>

#include <Box2D/Common/b2GrowableStack.h>

#include "Box2D/Collision/Shapes/c_b2PolygonShape.cpp"
#include "Box2D/Common/c_b2Math.cpp"
#include "Box2D/Dynamics/c_b2Body.cpp"
#include "Box2D/Dynamics/c_b2Fixture.cpp"
#include "Box2D/Dynamics/c_b2World.cpp"
#include "Box2D/Particle/c_b2Particle.cpp"
#include "Box2D/Particle/c_b2ParticleSystem.cpp"